package lain.mods.molanguage;

import java.util.Arrays;
import lain.mods.laincraft.util.ConfigUtils;
import net.minecraftforge.common.Configuration;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "MoLanguage", name = "MoLanguage", version = "1.0", dependencies = "required-after:LainCraft;after:*", useMetadata = false)
public class MoLanguage
{

    @ConfigUtils.SingleComment("dump all mod language data? (auto-reset after one successful dump)")
    private static boolean config_dump = false;
    @ConfigUtils.SingleComment("dump the specific language?")
    private static String config_dumpLang = "";
    @ConfigUtils.SingleComment("dump data imported by this mod?")
    private static boolean config_dumpExtra = false;
    @ConfigUtils.SingleComment("online lang-pack providers")
    private static String[] config_urlProviders = new String[0];
    @ConfigUtils.SingleComment("allow online lang-packs?")
    private static boolean config_allowDownload = true;

    @Mod.Metadata
    public static ModMetadata metadata;

    private Configuration config;

    @Mod.PreInit
    public void init(FMLPreInitializationEvent event)
    {
        metadata.authorList = Arrays.asList("Lain");
        metadata.description = "";
        metadata.parent = "LainCraft";
        metadata.autogenerated = false;
        config = new Configuration(event.getSuggestedConfigurationFile());
        config.load();
        ConfigUtils.loadFromConfig(config, getClass(), "config_", Configuration.CATEGORY_GENERAL);
        config.save();
    }

}
