package lain.mods.molanguage;

import java.util.Arrays;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "MoLanguage", name = "MoLanguage", version = "1.0", dependencies = "required-after:LainCraft", useMetadata = false)
public class MoLanguage
{

    @Mod.Metadata
    public static ModMetadata metadata;

    @Mod.PreInit
    public void init(FMLPreInitializationEvent event)
    {
        metadata.authorList = Arrays.asList("Lain");
        metadata.description = "";
        metadata.parent = "LainCraft";
        metadata.autogenerated = false;
    }

}
