package lain.mods.laincraft;

import java.util.Arrays;
import net.minecraft.util.StringUtils;
import com.google.common.eventbus.EventBus;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

public class LainCraft extends DummyModContainer
{

    public static boolean isLain(String username)
    {
        return "zlainsama".equalsIgnoreCase(StringUtils.stripControlCodes(username));
    }

    public LainCraft()
    {
        super(new ModMetadata());
        getMetadata();
    }

    @Override
    public ModMetadata getMetadata()
    {
        ModMetadata md = super.getMetadata();
        md.modId = "LainCraft";
        md.name = "LainCraft";
        md.version = "1.0";
        md.authorList = Arrays.asList("Lain");
        md.description = "";
        md.autogenerated = false;
        return md;
    }

    @Override
    public boolean registerBus(EventBus eventbus, LoadController controllor)
    {
        eventbus.register(this);
        return true;
    }

}
